// lib/git-engine/command-catalog.ts – Comprehensive Command Catalog

export type CommandDefinition = {
  name: string;
  aliases?: string[];
  category: 'porcelain' | 'plumbing' | 'ancillary';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  description: string;
  syntax: string;
  examples: string[];
  dangerous?: boolean;
  implemented: boolean;
  version?: string;
  related?: string[];
};

export const commandCatalog: CommandDefinition[] = [
  // ----------------------------------------------------
  // BEGINNER COMMANDS
  // ----------------------------------------------------
  {
    name: 'git config',
    category: 'ancillary',
    difficulty: 'beginner',
    description: 'Set and read repository or global configuration options such as author name, email, and aliases.',
    syntax: 'git config [--global|--local] <key> [value]',
    examples: [
      'git config --global user.name "Your Name"',
      'git config --global user.email "you@example.com"',
      'git config --list --show-origin',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git init', 'git help'],
  },
  {
    name: 'git init',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Create an empty Git repository or reinitialize an existing one by generating the .git metadata directory.',
    syntax: 'git init [<directory>] [--initial-branch=<name>]',
    examples: ['git init', 'git init my-project', 'git init --initial-branch=main'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git clone', 'git status'],
  },
  {
    name: 'git clone',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Clone a remote repository into a new local directory, establishing remote-tracking branches for all remote branches.',
    syntax: 'git clone [--depth <depth>] <repository-url> [<directory>]',
    examples: [
      'git clone https://github.com/org/project.git',
      'git clone git@github.com:org/project.git my-app',
      'git clone --depth 1 https://github.com/org/project.git',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git remote', 'git fetch', 'git pull'],
  },
  {
    name: 'git status',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Show the working tree status: staged changes, unstaged modifications, and untracked files.',
    syntax: 'git status [-s|--short] [-b|--branch]',
    examples: ['git status', 'git status -s', 'git status -sb'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git add', 'git diff', 'git commit'],
  },
  {
    name: 'git add',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Add file contents and modifications from the working tree to the staging area (index) for the next commit.',
    syntax: 'git add [<pathspec>...] [-A|--all] [-p|--patch]',
    examples: ['git add README.md', 'git add src/', 'git add .', 'git add -p'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git status', 'git restore', 'git commit'],
  },
  {
    name: 'git commit',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Record staged changes as a permanent snapshot in repository history with author metadata and a message.',
    syntax: 'git commit [-m <msg>] [-a] [--amend]',
    examples: [
      'git commit -m "feat: add user authentication"',
      'git commit -am "fix: correct navbar styling"',
      'git commit --amend --no-edit',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git add', 'git log', 'git show'],
  },
  {
    name: 'git log',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Show commit history logs reachable from HEAD with formatting, graphs, statistics, and filtering.',
    syntax: 'git log [--oneline] [--graph] [--decorate] [-n <count>]',
    examples: [
      'git log',
      'git log --oneline --graph --decorate',
      'git log -n 5 --stat',
      'git log --grep="auth" --oneline',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git show', 'git shortlog', 'git reflog'],
  },
  {
    name: 'git diff',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Show line-by-line changes between working tree, staging area, commits, or branches.',
    syntax: 'git diff [<commit>] [--staged|--cached] [-- <path>...]',
    examples: [
      'git diff',
      'git diff --staged',
      'git diff HEAD~1 HEAD',
      'git diff main..feature',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git status', 'git show', 'git log'],
  },
  {
    name: 'git show',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Show detailed metadata and unified patch diff for a specific commit, tag, tree, or file revision.',
    syntax: 'git show [<object>] [--stat]',
    examples: ['git show HEAD', 'git show 7a8b9c1', 'git show HEAD:package.json'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git log', 'git cat-file'],
  },
  {
    name: 'git restore',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Restore working tree files from index/commit, or unstage files from the index.',
    syntax: 'git restore [--staged] [--source=<commit>] <pathspec>...',
    examples: [
      'git restore --staged config.json',
      'git restore app.js',
      'git restore --source=HEAD~1 src/',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git reset', 'git checkout', 'git clean'],
  },
  {
    name: 'git rm',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Remove files from both the working tree and the staging index, or stop tracking files with --cached.',
    syntax: 'git rm [-f|--force] [-r] [--cached] <file>...',
    examples: [
      'git rm obsolete.js',
      'git rm --cached .env.local',
      'git rm -r build-output/',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git mv', 'git add', 'git restore'],
  },
  {
    name: 'git mv',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Move or rename a file, directory, or symlink and stage the change automatically.',
    syntax: 'git mv [-f] <source> <destination>',
    examples: ['git mv old-name.ts new-name.ts', 'git mv file.txt src/file.txt'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git rm', 'git add', 'git status'],
  },
  {
    name: 'git branch',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'List, create, rename, or delete branch reference pointers.',
    syntax: 'git branch [-a] [-d|-D <branch>] [-m <new-name>]',
    examples: [
      'git branch',
      'git branch -a',
      'git branch feature/auth',
      'git branch -d feature/auth',
      'git branch -m old-name new-name',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git switch', 'git checkout', 'git merge'],
  },
  {
    name: 'git switch',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Switch working branches or create and checkout new branches cleanly.',
    syntax: 'git switch [-c|--create <new-branch>] <branch-name>',
    examples: [
      'git switch main',
      'git switch -c feature/login',
      'git switch -',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git branch', 'git checkout', 'git restore'],
  },
  {
    name: 'git checkout',
    category: 'porcelain',
    difficulty: 'beginner',
    description: 'Switch branches, checkout specific historical commits (detached HEAD), or restore working tree files.',
    syntax: 'git checkout [-b <new-branch>] [<branch>|<commit>|<file>]',
    examples: [
      'git checkout main',
      'git checkout -b feature/search',
      'git checkout 7a8b9c1',
      'git checkout -- app.js',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git switch', 'git restore', 'git branch'],
  },
  {
    name: 'git help',
    category: 'ancillary',
    difficulty: 'beginner',
    description: 'Display official manual pages and command usage references.',
    syntax: 'git help [<command>] / git <command> --help',
    examples: ['git help', 'git help commit', 'git log --help'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git config'],
  },

  // ----------------------------------------------------
  // INTERMEDIATE COMMANDS
  // ----------------------------------------------------
  {
    name: 'git remote',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Manage the set of tracked remote repositories (such as origin or upstream).',
    syntax: 'git remote [-v] [add|remove|set-url|rename] <name> [<url>]',
    examples: [
      'git remote -v',
      'git remote add origin https://github.com/org/repo.git',
      'git remote set-url origin git@github.com:org/repo.git',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git fetch', 'git push', 'git pull'],
  },
  {
    name: 'git fetch',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Download objects, commits, and refs from a remote repository into local remote-tracking branches without merging.',
    syntax: 'git fetch [<remote>] [--all] [--prune]',
    examples: ['git fetch origin', 'git fetch --all --prune', 'git fetch origin main'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git pull', 'git remote', 'git branch'],
  },
  {
    name: 'git pull',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Fetch from and integrate with another repository or a local branch (fetch + merge/rebase).',
    syntax: 'git pull [<remote>] [<branch>] [--rebase] [--ff-only]',
    examples: [
      'git pull origin main',
      'git pull --rebase origin main',
      'git pull --ff-only',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git fetch', 'git merge', 'git rebase'],
  },
  {
    name: 'git push',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Upload local branch commits to the remote repository and advance the remote ref.',
    syntax: 'git push [-u] [<remote>] [<branch>] [--force-with-lease] [--tags]',
    examples: [
      'git push origin main',
      'git push -u origin feature/login',
      'git push origin --tags',
      'git push origin --delete old-feature',
    ],
    dangerous: true,
    implemented: true,
    version: '2.47+',
    related: ['git pull', 'git fetch', 'git remote'],
  },
  {
    name: 'git merge',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Join two or more development histories together via Fast-Forward or 3-Way Merge.',
    syntax: 'git merge [<branch>] [--no-ff] [--abort] [--squash]',
    examples: [
      'git merge feature/auth',
      'git merge --no-ff feature/auth',
      'git merge --abort',
      'git merge --squash feature/auth',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git rebase', 'git branch', 'git checkout'],
  },
  {
    name: 'git stash',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Stash uncommitted working directory and index modifications away onto a temporary stack.',
    syntax: 'git stash [push [-u] [-m <msg>]] [pop|apply|list|drop|clear]',
    examples: [
      'git stash',
      'git stash push -u -m "WIP form validation"',
      'git stash list',
      'git stash pop',
      'git stash apply stash@{0}',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git restore', 'git switch'],
  },
  {
    name: 'git tag',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Create, list, delete or verify tag objects signed with GPG or lightweight bookmarks.',
    syntax: 'git tag [-a <name> -m <msg>] [-d <name>] [-l [<pattern>]]',
    examples: [
      'git tag',
      'git tag -a v1.0.0 -m "Release version 1.0.0"',
      'git show v1.0.0',
      'git tag -d v0.9.0',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git show', 'git push'],
  },
  {
    name: 'git rebase',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Reapply commits on top of another base tip, maintaining a clean linear commit graph.',
    syntax: 'git rebase [-i] [<upstream>] [--continue|--abort|--skip]',
    examples: [
      'git rebase main',
      'git rebase -i HEAD~3',
      'git rebase --continue',
      'git rebase --abort',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git merge', 'git cherry-pick', 'git reflog'],
  },
  {
    name: 'git cherry-pick',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Apply the changes introduced by existing commits onto the current checked-out branch.',
    syntax: 'git cherry-pick [-x] [-n] <commit>...',
    examples: [
      'git cherry-pick 4a5b6c7',
      'git cherry-pick -x 4a5b6c7',
      'git cherry-pick --abort',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git rebase', 'git revert'],
  },
  {
    name: 'git revert',
    category: 'porcelain',
    difficulty: 'intermediate',
    description: 'Forward-undo existing commits by generating new commits with the exact opposite diff.',
    syntax: 'git revert [-n] [-m <parent-number>] <commit>...',
    examples: ['git revert HEAD', 'git revert 7a8b9c1', 'git revert -m 1 <merge-commit>'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git reset', 'git commit'],
  },
  {
    name: 'git reset',
    category: 'ancillary',
    difficulty: 'intermediate',
    description: 'Reset current HEAD to a specified state, altering the staging index and optionally working tree.',
    syntax: 'git reset [--soft|--mixed|--hard] [<commit>]',
    examples: [
      'git reset --soft HEAD~1',
      'git reset --mixed HEAD~1',
      'git reset --hard HEAD~1',
      'git reset --hard origin/main',
    ],
    dangerous: true,
    implemented: true,
    version: '2.47+',
    related: ['git restore', 'git revert', 'git reflog'],
  },
  {
    name: 'git reflog',
    category: 'ancillary',
    difficulty: 'intermediate',
    description: 'Manage and query reference logs recording every local HEAD and branch pointer update.',
    syntax: 'git reflog [show] [<ref>]',
    examples: ['git reflog', 'git reflog show main', 'git reset --hard HEAD@{2}'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git reset', 'git log'],
  },
  {
    name: 'git bisect',
    category: 'ancillary',
    difficulty: 'intermediate',
    description: 'Use binary search across commit history to identify the exact commit that introduced a bug.',
    syntax: 'git bisect [start|bad|good|reset|run] [<rev>]',
    examples: [
      'git bisect start',
      'git bisect bad HEAD',
      'git bisect good v1.0.0',
      'git bisect run npm test',
      'git bisect reset',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git log', 'git blame'],
  },
  {
    name: 'git blame',
    category: 'ancillary',
    difficulty: 'intermediate',
    description: 'Show what revision and author last modified each line of a file.',
    syntax: 'git blame [-L <start>,<end>] <file>',
    examples: [
      'git blame src/index.ts',
      'git blame -L 10,25 package.json',
      'git blame -w src/auth.ts',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git log', 'git shortlog'],
  },
  {
    name: 'git shortlog',
    category: 'ancillary',
    difficulty: 'intermediate',
    description: 'Summarize git log output grouped by author with commit counts.',
    syntax: 'git shortlog [-s] [-n] [-e] [--all]',
    examples: ['git shortlog -sn', 'git shortlog -sne --all'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git log', 'git blame'],
  },
  {
    name: 'git clean',
    category: 'ancillary',
    difficulty: 'intermediate',
    description: 'Remove untracked files and directories from the working tree.',
    syntax: 'git clean [-d] [-f] [-n|--dry-run] [-x]',
    examples: ['git clean -n -d', 'git clean -fd', 'git clean -fdx'],
    dangerous: true,
    implemented: true,
    version: '2.47+',
    related: ['git reset', 'git restore', 'git status'],
  },

  // ----------------------------------------------------
  // ADVANCED & PLUMBING COMMANDS
  // ----------------------------------------------------
  {
    name: 'git cat-file',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Provide content or type/size information for raw repository objects in the object store.',
    syntax: 'git cat-file (-p|-t|-s|-e) <object>',
    examples: [
      'git cat-file -p HEAD',
      'git cat-file -t 3b18e51',
      'git cat-file -s 3b18e51',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git hash-object', 'git ls-tree'],
  },
  {
    name: 'git hash-object',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Compute object ID and optionally create a blob object from a file or standard input.',
    syntax: 'git hash-object [-w] [-t <type>] [--stdin] <file>',
    examples: [
      'git hash-object README.md',
      'echo "hello" | git hash-object -w --stdin',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git cat-file', 'git write-tree'],
  },
  {
    name: 'git ls-tree',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'List the contents of a tree object, including modes, types, hashes, and filenames.',
    syntax: 'git ls-tree [-r] [-t] [-d] <tree-ish> [<path>...]',
    examples: ['git ls-tree HEAD', 'git ls-tree -r HEAD', 'git ls-tree -r -t HEAD'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git write-tree', 'git cat-file'],
  },
  {
    name: 'git write-tree',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Create a tree object from the current staging index.',
    syntax: 'git write-tree [--missing-ok] [--prefix=<prefix>/]',
    examples: ['git write-tree'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git commit-tree', 'git read-tree', 'git ls-tree'],
  },
  {
    name: 'git commit-tree',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Create a new commit object directly from a tree SHA and parent commit SHAs.',
    syntax: 'git commit-tree <tree> -m <msg> [-p <parent>...]',
    examples: ['git commit-tree 8a7b6c5 -m "Manual commit" -p HEAD'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git write-tree', 'git update-ref'],
  },
  {
    name: 'git read-tree',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Read tree information into the index buffer.',
    syntax: 'git read-tree [[-m [--trivial] [--aggressive] | --reset | --prefix=<prefix>] [-u | -i]] <tree-ish>',
    examples: ['git read-tree HEAD', 'git read-tree -m -u HEAD~1 HEAD'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git write-tree', 'git ls-tree'],
  },
  {
    name: 'git update-index',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Register file contents in the working tree to the staging index.',
    syntax: 'git update-index [--add] [--remove] [--assume-unchanged] <path>...',
    examples: [
      'git update-index --add file.txt',
      'git update-index --assume-unchanged config.json',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git add', 'git ls-files'],
  },
  {
    name: 'git ls-files',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Show information about files in the staging index and the working tree.',
    syntax: 'git ls-files [-s|--stage] [-m|--modified] [-u|--unmerged] [-o|--others]',
    examples: ['git ls-files', 'git ls-files -s', 'git ls-files -o --exclude-standard'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git status', 'git update-index'],
  },
  {
    name: 'git rev-parse',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Pick out and massage parameters, turning symbolic revisions into 40-character SHAs.',
    syntax: 'git rev-parse [--show-toplevel] [--verify] <args>...',
    examples: [
      'git rev-parse HEAD',
      'git rev-parse --show-toplevel',
      'git rev-parse --abbrev-ref HEAD',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git rev-list', 'git show-ref'],
  },
  {
    name: 'git rev-list',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'List commit objects in reverse chronological order according to DAG ancestry.',
    syntax: 'git rev-list [--count] [--oneline] <commit>...',
    examples: ['git rev-list --count HEAD', 'git rev-list --count main..feature'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git log', 'git rev-parse'],
  },
  {
    name: 'git show-ref',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'List references in a local repository along with their object IDs.',
    syntax: 'git show-ref [--heads] [--tags]',
    examples: ['git show-ref', 'git show-ref --heads', 'git show-ref --tags'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git for-each-ref', 'git update-ref'],
  },
  {
    name: 'git update-ref',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Update the object name stored in a ref safely and securely.',
    syntax: 'git update-ref [-m <reason>] <ref> <newvalue> [<oldvalue>]',
    examples: ['git update-ref refs/heads/main 7a8b9c1'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git symbolic-ref', 'git show-ref'],
  },
  {
    name: 'git symbolic-ref',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Read, modify and delete symbolic refs such as HEAD.',
    syntax: 'git symbolic-ref [-q] [-m <reason>] <name> [<ref>]',
    examples: ['git symbolic-ref HEAD', 'git symbolic-ref HEAD refs/heads/main'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git update-ref', 'git branch'],
  },
  {
    name: 'git for-each-ref',
    category: 'plumbing',
    difficulty: 'advanced',
    description: 'Output information on each ref with formatted custom template fields.',
    syntax: 'git for-each-ref [--sort=<key>] [--format=<format>] [<pattern>]',
    examples: [
      'git for-each-ref refs/heads/',
      'git for-each-ref --sort=-committerdate --format="%(committerdate:short) %(refname:short)"',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git show-ref', 'git branch'],
  },
  {
    name: 'git worktree',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Manage multiple working trees attached to the same repository.',
    syntax: 'git worktree [add|list|lock|unlock|move|prune|remove] [<path>] [<commit-ish>]',
    examples: [
      'git worktree list',
      'git worktree add ../hotfix main',
      'git worktree remove ../hotfix',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git branch', 'git switch'],
  },
  {
    name: 'git sparse-checkout',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Reduce working tree size in monorepos by populating only directories matching cone patterns.',
    syntax: 'git sparse-checkout [init|set|add|list|disable] [<patterns>...]',
    examples: [
      'git sparse-checkout init --cone',
      'git sparse-checkout set packages/frontend shared/ui',
      'git sparse-checkout list',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git clone', 'git checkout'],
  },
  {
    name: 'git submodule',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Initialize, update or inspect submodules embedded within repository subdirectories.',
    syntax: 'git submodule [add|status|init|update|sync] [--recursive] [<path>]',
    examples: [
      'git submodule add https://github.com/lib/core.git libs/core',
      'git submodule status',
      'git submodule update --init --recursive',
    ],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git clone', 'git subtree'],
  },
  {
    name: 'git subtree',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Merge subtrees together and split repository into subtrees as an alternative to submodules.',
    syntax: 'git subtree [add|pull|push|split] -P <prefix> <repository> <ref>',
    examples: ['git subtree add --prefix=libs/core https://github.com/lib/core.git main --squash'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git submodule', 'git merge'],
  },
  {
    name: 'git rerere',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Reuse recorded resolution of conflicted merges automatically across repetitive rebases.',
    syntax: 'git rerere [clear|forget|diff|remaining|status|gc]',
    examples: ['git config --global rerere.enabled true', 'git rerere status'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git merge', 'git rebase'],
  },
  {
    name: 'git gc',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Cleanup unnecessary files and optimize the local repository object store.',
    syntax: 'git gc [--prune=<date>|--aggressive|--auto]',
    examples: ['git gc', 'git gc --prune=now', 'git gc --aggressive'],
    dangerous: true,
    implemented: true,
    version: '2.47+',
    related: ['git prune', 'git repack', 'git count-objects'],
  },
  {
    name: 'git prune',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Prune all unreachable objects from the object database.',
    syntax: 'git prune [-n] [-v] [--expire <time>]',
    examples: ['git prune -n', 'git prune --expire=now'],
    dangerous: true,
    implemented: true,
    version: '2.47+',
    related: ['git gc', 'git fsck'],
  },
  {
    name: 'git repack',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Pack unpacked loose objects in a repository into compressed packfiles.',
    syntax: 'git repack [-a] [-d] [-f] [-F]',
    examples: ['git repack -a -d'],
    dangerous: true,
    implemented: true,
    version: '2.47+',
    related: ['git gc', 'git count-objects'],
  },
  {
    name: 'git count-objects',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Count unpacked object number and disk consumption.',
    syntax: 'git count-objects [-v] [-H]',
    examples: ['git count-objects -vH'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git gc', 'git repack'],
  },
  {
    name: 'git fsck',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Verifies the connectivity and validity of the objects in the database.',
    syntax: 'git fsck [--full] [--unreachable] [--lost-found]',
    examples: ['git fsck --full', 'git fsck --lost-found'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git prune', 'git gc'],
  },
  {
    name: 'git maintenance',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Run background maintenance tasks to optimize Git repository data and performance.',
    syntax: 'git maintenance [start|stop|run|register|unregister]',
    examples: ['git maintenance start', 'git maintenance run --task=gc'],
    dangerous: false,
    implemented: true,
    version: '2.47+',
    related: ['git gc', 'git count-objects'],
  },
  {
    name: 'git archive',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Create a zip or tar archive of files from a named tree or commit revision.',
    syntax: 'git archive --format=<zip|tar> --output=<filename> <tree-ish>',
    examples: ['git archive --format=zip --output=release.zip HEAD'],
    dangerous: false,
    implemented: false,
    version: '2.47+',
    related: ['git tag', 'git show'],
  },
  {
    name: 'git bundle',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Move objects and refs by packaging Git history into single binary archive files.',
    syntax: 'git bundle [create|verify|list-heads|unbundle] <file> [<git-rev-list-args>]',
    examples: ['git bundle create repo.bundle --all', 'git bundle verify repo.bundle'],
    dangerous: false,
    implemented: false,
    version: '2.47+',
    related: ['git clone', 'git fetch'],
  },
  {
    name: 'git credential',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Retrieve, store, and manage user credentials for remote authentication.',
    syntax: 'git credential [fill|approve|reject]',
    examples: ['git config --global credential.helper osxkeychain'],
    dangerous: false,
    implemented: false,
    version: '2.47+',
    related: ['git config', 'git remote'],
  },
  {
    name: 'git check-ignore',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Debug and verify which .gitignore rules pattern match specific paths.',
    syntax: 'git check-ignore [-v] <pathname>...',
    examples: ['git check-ignore -v src/temp.log'],
    dangerous: false,
    implemented: false,
    version: '2.47+',
    related: ['git status', 'git ls-files'],
  },
  {
    name: 'git merge-base',
    category: 'ancillary',
    difficulty: 'advanced',
    description: 'Find as good common ancestors as possible for a merge.',
    syntax: 'git merge-base <commit> <commit>',
    examples: ['git merge-base main feature/login'],
    dangerous: false,
    implemented: false,
    version: '2.47+',
    related: ['git merge', 'git log'],
  },
];

export function findCommand(q: string) {
  const n = q.trim().toLowerCase();
  if (!n) return commandCatalog;
  return commandCatalog.filter(
    (c) =>
      c.name.toLowerCase().includes(n) ||
      c.description.toLowerCase().includes(n) ||
      c.category.toLowerCase().includes(n) ||
      c.difficulty.toLowerCase().includes(n),
  );
}
