import { cloneRepo, commonAncestor, createCommit, currentCommit, oid, recordRef, type RepoState, short, checkoutCommitFiles, headFiles } from './core';
export type Result={output:string;error?:boolean;state:RepoState};
export type ExecContext={author?:string};
const ok=(r:RepoState,output:string):Result=>({output,state:r}); const err=(r:RepoState,output:string):Result=>({output,error:true,state:r});
function parsePath(arg:string){return arg.replace(/^['"]|['"]$/g,'');}
function resolveCommitish(r:RepoState, value:string):string|undefined {
  if (!value) return undefined;
  if (value === 'HEAD') return currentCommit(r);
  if (value in r.commits) return value;
  const refName = value.startsWith('refs/') ? value : (value.startsWith('heads/') ? value : undefined);
  if (refName && r.refs[refName]) return r.refs[refName];
  if (value.startsWith('HEAD~')) {
    const steps = Number.parseInt(value.slice(5), 10);
    if (Number.isNaN(steps) || steps < 0) return undefined;
    let current = currentCommit(r);
    let remaining = steps;
    while (current && remaining > 0) {
      const commit = r.commits[current];
      if (!commit || !commit.parentIds.length) return undefined;
      current = commit.parentIds[0];
      remaining -= 1;
    }
    return current;
  }
  if (value.startsWith('HEAD^')) {
    const commit = r.commits[currentCommit(r)];
    return commit?.parentIds[0];
  }
  const directRef = r.refs[value] ?? r.refs[`heads/${value}`] ?? r.refs[`tags/${value}`];
  if (directRef) return directRef;
  return Object.keys(r.commits).find((id) => id.startsWith(value));
}
export function executeGit(input:string, initial:RepoState, ctx:ExecContext={}):Result { const r=cloneRepo(initial); const parts=input.trim().split(/\s+/); if(parts[0]!=='git') return err(r,`bash: ${parts[0]??''}: command not found`); const cmd=parts[1]??''; const args=parts.slice(2);
 if(cmd==='init'){r.initialized=true;r.branch='main';r.refs['heads/main']='';r.head='main';r.headSymbolic=true;r.detached=false;return ok(r,'Initialized empty Git repository in /gitnovi/.git/');}
 if(!r.initialized && !['--version','help','config'].includes(cmd)) return err(r,'fatal: not a git repository (or any of the parent directories): .git');
 if(cmd==='--version')return ok(r,'git version 2.47.3 (GitNovi simulator)');
 if(cmd==='status'){const head=headFiles(r);const staged=Object.keys(r.index).filter(k=>head[k]!==r.index[k]||!(k in head));const modified=Object.keys(r.files).filter(k=>k in r.index&&r.index[k]!==r.files[k]);const untracked=Object.keys(r.files).filter(k=>!(k in r.index)&&!(k in head));const deleted=Object.keys(head).filter(k=>!(k in r.files)&&!(k in r.index));const branch=r.detached?'HEAD':r.branch;let out=`On branch ${branch}\n`; if(staged.length)out+='\nChanges to be committed:\n\tmodified: '+staged.join('\n\tmodified: ')+'\n'; if(modified.length)out+='\nChanges not staged for commit:\n\tmodified: '+modified.join('\n\tmodified: ')+'\n'; if(deleted.length)out+='\nChanges not staged for commit:\n\tdeleted: '+deleted.join('\n\tdeleted: ')+'\n'; if(untracked.length)out+='\nUntracked files:\n\t'+untracked.join('\n\t')+'\n'; if(!staged.length&&!modified.length&&!untracked.length&&!deleted.length)out+='\nnothing to commit, working tree clean'; return ok(r,out);}
 if(cmd==='config'){return ok(r,args.length?`Configured ${args.join(' ')}`:'');}
 if(cmd==='add'){const target=args.find(a=>!a.startsWith('-')); const all=args.includes('-A')||args.includes('--all'); if(!target&&!all)return err(r,'Nothing specified, nothing added.'); const paths=all||target==='.'?Object.keys(r.files):[parsePath(target!)]; for(const p of paths)if(p in r.files)r.index[p]=r.files[p]; return ok(r,'');}
 if(cmd==='commit'){const mi=args.indexOf('-m');const msg=mi>=0?args.slice(mi+1).join(' ').replace(/^['"]|['"]$/g,''):''; if(!msg)return err(r,'error: switch `m` requires a value'); if(!Object.keys(r.index).length)return err(r,'nothing to commit, working tree clean');const id=createCommit(r,msg,ctx.author);return ok(r,`[${r.branch} ${short(id)}] ${msg}`);}
 if(cmd==='log'){let id=args.includes('--all')?Object.values(r.refs).find(Boolean)??currentCommit(r):currentCommit(r); if(!id)return ok(r,'');const lines=[];let n=0;while(id&&n<50){const c=r.commits[id];if(!c)break;lines.push(`commit ${id}${id===currentCommit(r)?' (HEAD -> '+r.branch+')':''}\nAuthor: ${c.author}\n\n    ${c.message}`);id=c.parentIds[0];n++;}return ok(r,lines.join('\n\n'));}
 if(cmd==='show'){const id=args[0]||currentCommit(r);const c=r.commits[id]||r.commits[Object.keys(r.commits).find(x=>x.startsWith(id))??''];if(!c)return err(r,`fatal: bad object ${id}`);return ok(r,`commit ${c.id}\nAuthor: ${c.author}\n\n    ${c.message}`);}
 if(cmd==='diff'||cmd==='restore'||cmd==='rm'||cmd==='mv'){ if(cmd==='diff'){return ok(r,'');} if(cmd==='restore'){const staged=args.includes('--staged');const p=args.find(a=>!a.startsWith('-'));if(staged&&p)delete r.index[p];else if(p&&p in r.index)r.files[p]=r.index[p];return ok(r,'');} if(cmd==='rm'){const p=args.find(a=>!a.startsWith('-'));if(p){delete r.files[p];delete r.index[p];}return ok(r,'');} if(cmd==='mv'){const a=args.find(x=>!x.startsWith('-'));const i=args.findIndex(x=>x===a);const b=args[i+1];if(a&&b&&a in r.files){r.files[b]=r.files[a];delete r.files[a];r.index[b]=r.index[a];delete r.index[a];}return ok(r,'');}}
 if(cmd==='branch'){if(!args.length)return ok(r,Object.keys(r.refs).filter(k=>k.startsWith('heads/')).map(k=>`${k.slice(6)===r.branch?'* ': '  '}${k.slice(6)}`).join('\n'));const name=args.find(a=>!a.startsWith('-'))!;if(args.includes('-d')||args.includes('-D')){delete r.refs[`heads/${name}`];return ok(r,`Deleted branch ${name}`);}if(args.includes('-m')){const old=r.branch;delete r.refs[`heads/${old}`];r.refs[`heads/${name}`]=currentCommit(r);r.branch=name;return ok(r,'');}r.refs[`heads/${name}`]=currentCommit(r);return ok(r,'');}
 if(cmd==='switch'||cmd==='checkout'){let name=args.find(a=>!a.startsWith('-')&&!['-b'].includes(a));if(args.includes('-b')){name=args[args.indexOf('-b')+1];r.refs[`heads/${name}`]=currentCommit(r);r.branch=name;r.detached=false;checkoutCommitFiles(r,currentCommit(r));return ok(r,`Switched to a new branch '${name}'`);}if(name&&r.refs[`heads/${name}`]!==undefined){r.branch=name;r.detached=false;r.head=name;checkoutCommitFiles(r,currentCommit(r));return ok(r,`Switched to branch '${name}'`);}if(name&&r.commits[name]){r.detached=true;r.head=name;checkoutCommitFiles(r,name);return ok(r,`Note: switching to '${name}'.\nYou are in 'detached HEAD' state.`);}return err(r,`error: pathspec '${name??''}' did not match any file(s) known to git`);}
 if(cmd==='merge'){const target=args.find(a=>!a.startsWith('-'));if(!target||r.refs[`heads/${target}`]===undefined)return err(r,`merge: ${target??''} - not something we can merge`);const ours=currentCommit(r),theirs=r.refs[`heads/${target}`];if(!theirs)return err(r,'fatal: refusing to merge unrelated histories');if(theirs===ours)return ok(r,'Already up to date.');if(commonAncestor(r,ours,theirs)===ours){r.refs[`heads/${r.branch}`]=theirs;checkoutCommitFiles(r,theirs);return ok(r,`Updating ${short(ours)}..${short(theirs)}\nFast-forward`);}const base=commonAncestor(r,ours,theirs);if(base&&r.commits[ours]&&r.commits[theirs]){const id=createCommit(r,`Merge branch '${target}'`,ctx.author);return ok(r,`Merge made by the 'ort' strategy.\n[${r.branch} ${short(id)}] Merge branch '${target}'`);}return err(r,'Automatic merge failed; fix conflicts and then commit the result.');}
 if(cmd==='revert'){const id=args.find(a=>!a.startsWith('-'));if(!id||!r.commits[id])return err(r,`fatal: bad object ${id??''}`);const c=r.commits[id];const newId=createCommit(r,`Revert "${c.message}"`,ctx.author);return ok(r,`[${r.branch} ${short(newId)}] Revert "${c.message}"`);}
 if(cmd==='reset'){const id=args.find(a=>!a.startsWith('-'));if(!id)return err(r,'fatal: ambiguous argument');const targetId=resolveCommitish(r,id);if(!targetId)return err(r,`fatal: bad object ${id}`);const target=r.commits[targetId];const old=currentCommit(r);r.refs[`heads/${r.branch}`]=target.id;recordRef(r,`heads/${r.branch}`,old,target.id,`reset: moving to ${target.id}`);if(args.includes('--hard'))checkoutCommitFiles(r,target.id);return ok(r,'');}
 if(cmd==='reflog'){const ref=`heads/${r.branch}`;return ok(r,(r.reflogs[ref]??[]).map((x,i)=>`${short(x.newId)} HEAD@{${i}}: ${x.message}`).join('\n'));}
 if(cmd==='remote'){if(!args.length)return ok(r,Object.keys(r.remotes).join('\n'));const sub=args[0];if(sub==='-v')return ok(r,Object.keys(r.remotes).map(n=>`${n}\tvirtual://${n} (fetch)\n${n}\tvirtual://${n} (push)`).join('\n'));if(sub==='add'){const n=args[1];if(n){r.remotes[n]={name:n,branches:{main:currentCommit(r)}};}return ok(r,'');}if(sub==='remove'){delete r.remotes[args[1]];return ok(r,'');}}
 if(cmd==='fetch'||cmd==='pull'||cmd==='push'){const remote=args.find(a=>!a.startsWith('-'))||'origin';if(!r.remotes[remote])return err(r,`fatal: '${remote}' does not appear to be a git repository`);if(cmd==='push'){r.remotes[remote].branches[r.branch]=currentCommit(r);return ok(r,`Everything up-to-date`);}if(cmd==='fetch')return ok(r,`From virtual://${remote}\n * [new branch]      main -> ${remote}/main`);return ok(r,'Already up to date.');}
 if(cmd==='stash'){const sub=args[0];if(!sub||sub==='push'){r.stash.unshift({id:oid(JSON.stringify(r.files)+Date.now()),files:{...r.files},index:{...r.index},message:args.slice(1).join(' ')||'WIP'});const c=currentCommit(r);if(c)checkoutCommitFiles(r,c);return ok(r,'Saved working directory and index state WIP');}if(sub==='list')return ok(r,r.stash.map((s,i)=>`stash@{${i}}: On ${r.branch}: ${s.message}`).join('\n'));if(sub==='pop'||sub==='apply'){const s=r.stash[0];if(!s)return err(r,'No stash entries found.');r.files={...s.files};r.index={...s.index};if(sub==='pop')r.stash.shift();return ok(r,'');}if(sub==='drop'){r.stash.shift();return ok(r,'Dropped stash@{0}');}if(sub==='clear'){r.stash=[];return ok(r,'');}}
 if(cmd==='tag'){const name=args.find(a=>!a.startsWith('-'));if(!name)return ok(r,Object.keys(r.refs).filter(k=>k.startsWith('tags/')).map(k=>k.slice(5)).join('\n'));if(args.includes('-d'))delete r.refs[`tags/${name}`];else r.refs[`tags/${name}`]=currentCommit(r);return ok(r,'');}
 if(cmd==='cat-file'||cmd==='hash-object'||cmd==='rev-parse'||cmd==='show-ref'||cmd==='for-each-ref'||cmd==='rev-list'||cmd==='ls-tree'||cmd==='ls-files'||cmd==='count-objects'||cmd==='fsck'||cmd==='update-ref'||cmd==='symbolic-ref'||cmd==='write-tree'||cmd==='read-tree'||cmd==='update-index'||cmd==='gc'||cmd==='prune'||cmd==='repack'||cmd==='maintenance'||cmd==='rerere'||cmd==='worktree'||cmd==='sparse-checkout'||cmd==='submodule'||cmd==='notes'||cmd==='replace'||cmd==='bisect'||cmd==='cherry-pick'||cmd==='rebase'||cmd==='reset'){ return ok(r,`GitNovi simulator: ${cmd} accepted for educational workflow.`); }
 if(cmd==='help'||!cmd)return ok(r,'usage: git [--version] [command]\n\nGitNovi includes an extensible educational Git command catalog.');
 return err(r,`git: '${cmd}' is not a GitNovi-simulated command.\nGitNovi currently does not simulate this command. Use Command Explorer or Ask AI for the real Git behavior.`);
}
export function runShell(input:string,r:RepoState):Result { const parts=input.trim().split(/\s+/); const cmd=parts[0]; const out=cloneRepo(r); if(['pwd'].includes(cmd))return ok(out,'/'); if(cmd==='ls')return ok(out,Object.keys(out.files).sort().join('  ')); if(cmd==='mkdir'){return ok(out,'');} if(cmd==='touch'){for(const p of parts.slice(1))out.files[p]={...out.files}[p]??'';return ok(out,'');} if(cmd==='cat'){const p=parts[1];return p in out.files?ok(out,out.files[p]):err(out,`cat: ${p}: No such file or directory`);} if(cmd==='echo'){const m=input.match(/^echo\s+(.+?)\s*>\s*(.+)$/);if(m){out.files[m[2]]=m[1].replace(/^['"]|['"]$/g,'');return ok(out,'');}return ok(out,parts.slice(1).join(' '));} if(cmd==='clear')return ok(out,''); return executeGit(input,out); }
